appdata = {
    "Google": "com.google.android.googlequicksearchbox",
    "Google Chrome": "com.android.chrome",
    "Instagram": "com.instagram.android",
    "Facebook": "com.facebook.katana",
    "YouTube": "com.google.android.youtube",
    "YouTube Music": "com.google.android.apps.youtube.music",
    "Telegram": "org.telegram.messenger",
    "Spotify": "com.spotify.music",
    "Netflix": "com.netflix.mediaclient",
    "Amazon": "com.amazon.mShop.android.shopping",
    "Flipkart": "com.flipkart.android",
    "Swiggy": "in.swiggy.android",
    "Zomato": "com.application.zomato",
    "Uber": "com.ubercab",
    "OLA": "com.olacabs.customer",
    "Twitter": "com.twitter.android",
    "Snapchat": "com.snapchat.android",
    "WhatsApp": "com.whatsapp",
    "Discord": "com.discord",
    "Reddit": "com.reddit.frontpage",
    "Netflix": "com.netflix.mediaclient",
    "Amazon Prime Video": "com.amazon.avod.thirdpartyclient",
    "Kinemaster": "com.nexstreaming.app.kinemasterfree",
    "Meesho": "com.meesho.supply",
    "OLX": "com.olx.southeastasia",
    "Spotify": "com.spotify.music",
    "Snaptube": "com.snaptube.premium",
    "VLC Media Player": "org.videolan.vlc",
    "Tor Browser": "org.torproject.torbrowser",
    "Brave Browser": "com.brave.browser",
    "Authenticator": "com.google.android.apps.authenticator2",
    "Candy Crush": "com.king.candycrushsaga",
    "Duolingo": "com.duolingo",
    "DeepSeek": "com.deepseek.chat",  # Placeholder, as this app may not exist
    "Gemini": "com.google.android.apps.bard",  # Placeholder
    "Metamask": "io.metamask",
    "Surfshark VPN": "com.surfshark.vpnclient",
    "Bitget Wallet": "com.bitget.wallet",
    "Ton Keeper": "com.ton_keeper",  # Placeholder
    "Mises Browser": "com.mises.browser",  # Placeholder
    "QPython": "com.qpython.py",
    "Pydroid": "com.chaquo.pydroid3",
    "CXXDroid": "com.n0n3m4.droidc",
    "Auto Clicker": "com.truedevelopersstudio.autoclicker",
    "Artist Grid": "com.artistgrid",  # Placeholder
    "Alibaba": "com.alibaba.aliexpresshd",
    "Big Basket": "com.bigbasket",
    "Zepto": "com.zepto",
    "Fampay": "com.fampay.in",
    "iBis Paint X": "jp.ne.ibis.ibispaintx.app",
    "ZArchiver": "ru.zdevs.zarchiver",
    "Hill Climb Racing": "com.fingersoft.hillclimb",
    "Gmail": "com.google.android.gm",
    "Google Drive": "com.google.android.apps.docs",
    "Authenticator": "com.google.android.apps.authenticator2",
    "CWallet": "com.cwallet",  # Placeholder
    "Copilot": "com.copilot",  # Placeholder
    "MXC": "com.mexc.global",  # Placeholder
    "Where is My Train": "com.whereismytrain.android",
    "Vivo Themes": "com.vivo.theme",  # Placeholder
    "BGMI": "com.pubg.imobile",
    "pubg": "com.pubg.imobile",
    "Alight Motion": "com.alightcreative.motion",
    "YouTube Studio": "com.google.android.apps.youtube.creator",
    "Reddit": "com.reddit.frontpage",
    "Kiwi Browser": "com.kiwibrowser.browser",
    "Kinemaster": "com.nexstreaming.app.kinemasterfree",
    "Meesho": "com.meesho.supply",
    "OLX": "com.olx.southeastasia",
    "Snaptube": "com.snaptube.premium",
    "VLC Media Player": "org.videolan.vlc",
    "Tor Browser": "org.torproject.torbrowser",
    "Brave Browser": "com.brave.browser",
    "Authenticator": "com.google.android.apps.authenticator2",
    "Candy Crush": "com.king.candycrushsaga",
    "Duolingo": "com.duolingo",
    "DeepSeek": "com.deepseek",  # Placeholder
    "Gemini": "com.gemini.ai",  # Placeholder
    "Metamask": "io.metamask",
    "Surfshark VPN": "com.surfshark.vpnclient",
    "Bitget Wallet": "com.bitget.wallet",
    "Ton Keeper": "com.tonkeeper",  # Placeholder
    "Mises Browser": "com.mises.browser",  # Placeholder
    "QPython": "com.qpython.py",
    "Pydroid": "com.chaquo.pydroid3",
    "CXXDroid": "com.n0n3m4.droidc",
    "Auto Clicker": "com.truedevelopersstudio.autoclicker",
    "Artist Grid": "com.artistgrid",  # Placeholder
    "Alibaba": "com.alibaba.aliexpresshd",
    "Big Basket": "com.bigbasket",
    "Zepto": "com.zepto",
    "Fampay": "com.fampay.in",
    "iBis Paint X": "jp.ne.ibis.ibispaintx.app",
    "ZArchiver": "ru.zdevs.zarchiver",
    "Hill Climb Racing": "com.fingersoft.hillclimb",
    "Gmail": "com.google.android.gm",
    "Google Drive": "com.google.android.apps.docs",
    "Authenticator": "com.google.android.apps.authenticator2",
    "CWallet": "com.cwallet",  # Placeholder
    "Copilot": "com.copilot",  # Placeholder
    "MXC": "com.mexc.global",  # Placeholder
    "Where is My Train": "com.whereismytrain.android",
    "Vivo Themes": "com.vivo.theme",  # Placeholder
    "BGMI": "com.pubg.imobile",
    "Alight Motion": "com.alightcreative.motion",
    "YouTube Studio": "com.google.android.apps.youtube.creator",
    "dialler": "com.google.android.dialer",
    "messages": "com.google.android.apps.messaging",
    "camera": "com.android.camera",
    "gallery": "com.vivo.gallery",
    "contacts": "com.google.android.contacts",
    "calculator": "com.google.android.calculator",
    "clock": "com.google.android.deskclock",
    "calendar": "com.google.android.calendar",
    "files": "com.google.android.apps.nbu.files",
    "maps": "com.google.android.apps.maps",
    "play store": "com.android.vending",
    "playstore": "com.android.vending",
    "settings": "com.android.settings",
    "settings app": "com.android.settings",
    "dialer": "com.google.android.dialer",

}